# Unified AI SDK - Static Analysis Configuration
#
# This file configures the static analysis results for the unified_ai_sdk project.
# It enables strict type checking, enhanced linter rules, and code quality metrics.
#
# For more information, see:
# https://dart.dev/guides/language/analysis-options

# Include the recommended set of lints from package:lints
# This set helps identify many issues and enforces idiomatic Dart style.
include: package:lints/recommended.yaml

# Analyzer configuration
analyzer:
  # Enable strict type checking for better type safety
  language:
    strict-casts: true # Prevents unsafe casts
    strict-inference: true # Requires explicit types where inference is unclear
    strict-raw-types: true # Prevents using raw types

  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart" # Generated files (build_runner, mockito)
    - "**/*.freezed.dart" # Freezed generated files
    - "**/*.pb.dart" # Protocol buffer generated files
    - "**/*.pbjson.dart" # Protocol buffer JSON files
    - "lib/src/**/*.objectbox.dart" # ObjectBox generated files
    - ".dart_tool/**" # Dart tool files
    - "build/**" # Build output directory

  # Error severity configuration
  errors:
    # Treat these as errors (strict)
    invalid_assignment: error
    invalid_null_aware_operator: error
    missing_required_param: error
    missing_return: error
    undefined_class: error
    undefined_method: error
    undefined_getter: error
    undefined_setter: error

    # Allow TODO comments (warnings are fine)
    todo: ignore

    # Treat deprecated member usage as warnings
    deprecated_member_use: warning

# Linter rules - Additional rules beyond the recommended set
linter:
  rules:
    # Documentation and API rules
    - always_declare_return_types # Explicit return types improve clarity
    - public_member_api_docs # Require documentation for public APIs

    # Null safety rules
    - avoid_null_checks_in_equality_operators # Prevent null-related bugs
    - prefer_null_aware_operators # Use null-aware operators
    - unnecessary_null_checks # Remove redundant null checks
    - prefer_if_null_operators # Use ?? operator

    # Code quality rules
    - avoid_print # Use proper logging instead
    - avoid_relative_lib_imports # Prefer package imports
    - prefer_const_constructors # Performance optimization
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields # Immutability where possible
    - prefer_final_locals # Prefer final for local variables
    - prefer_single_quotes # Consistent string quotes
    - sort_pub_dependencies # Keep pubspec.yaml organized

    # Error handling rules
    - avoid_catches_without_on_clauses # Catch specific exceptions
    - avoid_catching_errors # Don't catch Error types
    - only_throw_errors # Only throw Error/Exception types

    # Code organization rules
    - prefer_is_empty # Use isEmpty over length == 0
    - prefer_is_not_empty # Use isNotEmpty over length > 0
    - prefer_contains # Use contains over indexOf != -1

    # Naming conventions
    - camel_case_types # Class names in CamelCase
    - non_constant_identifier_names # Variables not in CONSTANT_CASE
    - constant_identifier_names # Constants in CONSTANT_CASE

    # Unused code detection
    - cancel_subscriptions # Cancel StreamSubscriptions
    - close_sinks # Close StreamControllers

    # Security and best practices
    - use_build_context_synchronously # Avoid async BuildContext usage (if Flutter)
    - avoid_empty_else # Don't use empty else blocks
    - prefer_typing_uninitialized_variables # Explicit types for uninitialized vars

# Code metrics configuration
# Note: Some metrics are handled by the linter rules above.
# For additional metrics, consider using dart_code_metrics package in the future.
